runners: jlink: Fix NoneType object error
The commit 8b7d3bb98f90fa53d87e0d9074d853d971bb87f8 presents a bug that
makes west flash failed with error.

AttributeError: 'NoneType' object has no attribute 'startswith'

In function is_tunnel(), tunnel may contain None and has no attribute
"startswith". Fix it.

Signed-off-by: Phi Bang Nguyen <phibang.nguyen@nxp.com>