boards: particle: fix BT selection
When selecting BT we need to select BT_CTRL for most bluetooth
samples to work correctly.

Let's fix that in the board files.

Fixes the following error when CONFIG_BT is selected:
zephyr/drivers/bluetooth/hci/h4.c:463:30:
error: ‘CONFIG_BT_UART_ON_DEV_NAME’ undeclared (first use in
this function)
  h4_dev = device_get_binding(CONFIG_BT_UART_ON_DEV_NAME);
                              ^~~~~~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Michael Scott <mike@foundries.io>